### ISSUE TITLE
LLDB JIT debugging problems

### ISSUE THREAD

**Issue by Keno** [Keno/Gallium.jl#1]
Once upon a time LLDB's sections kept a private copy of the section data. The JIT debugging code made use of this to relocate the object file when loading a JIT object. However, unfortunately, this no longer seems to be the case, so JIT debugging is broken (haven't noticed so far, since sys.dylib still works). The proper way to fix this is probably to add RelocAddrMap support to LLDB's DWARF parser. Currently looking into some more hacky solutions.

**Comment by ihnorton** [comment]
@Keno the following commit appears to improve the LLDB JIT backtrace situation. (`SavedObject.getBinary()` succeeds in `operator()` in JuliaListener, so we are able to call `NotifyGDB`):

http://reviews.llvm.org/D15172

before:
```
(lldb) bt
* thread #1: tid = 0xc6a0fe, 0x0000000100046d11 libjulia-debug.dylib`jl_backtrace_from_here + 49 at task.c:715, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000100046d11 libjulia-debug.dylib`jl_backtrace_from_here + 49 at task.c:715
    frame #1: 0x0000000311773090 JIT(0x3070c9630)`??? + 144
```

after:
```
(lldb) bt
* thread #1: tid = 0xc312db, 0x000000010002eed2 libjulia.dylib`jl_backtrace_from_here + 34 at task.c:715, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x000000010002eed2 libjulia.dylib`jl_backtrace_from_here + 34 at task.c:715 [opt]
    frame #1: 0x0000000310f7707b JIT(0x102470c30)`julia_bar_23610 + 123 at none:1 [opt]
    frame #2: 0x0000000310f770a6 JIT(0x102470c30)`jlcall_bar_23610 + 22
```

The LLDB Makefile is broken on master, but I applied the change to LLDB 3.7.1, and got the above improvement.

**Comment by ihnorton** [comment]
(patch submitted to fix LLDB Makefile build: http://reviews.llvm.org/D16284)

**Comment by Keno** [comment]
Not using LLDB anymore.
