### ISSUE TITLE
Breakpoints on locations inside @async blocks break Debugger REPL

### ISSUE THREAD

**Issue by tehrengruber** [Keno/Gallium.jl#101]
Minimum example to reproduce the bug (pretty self explanatory)
```
using Gallium
@noinline function bla()
    1
end
breakpoint(bla)

# everything works fine
bla()

# doesn't work
# pressing `n` results in
# Unknown command!
# 1|debug >
@async bla()
```

Platform info:

```
Julia Version 0.5.0-dev+4075
Commit 374b138 (2016-05-13 09:41 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

Gallium version: 5ccf1d76d2353f5e09de4029604f11d3af207628 (current master)
ASTInterpreter version: db844242943a0edf136175b732ac07515bf5eb43 (current master)

**Comment by Keno** [comment]
I don't understand what you are attempting to do. The `1|debug >` prompt is not a julia prompt. You have to hit ``` ` ``` to get the julia prompt for the local frame (or quit the debugger again using ^D).

**Comment by tehrengruber** [comment]
I'm trying to debug code that is scheduled asynchronous. But doing so is not possible since the REPL of the debugger does not work properly in such cases. You can try my example and press `n` to proceed execution. In the first case everything is fine. In the second case you will recieve `Unknown command!` and other strange stuff happens.

**Comment by Keno** [comment]
I see, thanks.
