### ISSUE TITLE
Unable to install Gallium using Julia v0.4.6

### ISSUE THREAD

**Issue by kkruups** [Keno/Gallium.jl#139]
**Problem:** Unable to install Gallium using Julia v0.4.6
The error below is indicated when performing a Pkg.add of Gallium.

Is Julia v0.4.6 not supported?

**Error Indicated**

julia> Pkg.add("Gallium")
ERROR: Gallium can't be installed because it has no versions that support 0.4.6 of julia. You may need to u
pdate METADATA by running `Pkg.update()`
 in error at error.jl:22
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

**Environment**

Windows 7
Julia v0.4.6

**Additional Info**

Other Packages install w/o issue.

Pkg.status info:

julia> Pkg.status()
1 required packages:
 - Gadfly                        0.4.2
39 additional packages:
 - BinDeps                       0.3.23
 - Calculus                      0.1.15
 - Codecs                        0.1.5
 - ColorTypes                    0.2.4
 - Colors                        0.6.5
 - Compat                        0.8.6
 - Compose                       0.4.2
 - Contour                       0.1.0
 - DataArrays                    0.3.6
 - DataFrames                    0.7.6
 - DataStructures                0.4.4
 - Dates                         0.4.4
 - Distances                     0.3.1
 - Distributions                 0.10.0
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.2.2
 - GZip                          0.2.19
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Iterators                     0.1.9
 - JSON                          0.6.0
 - KernelDensity                 0.1.2
 - Loess                         0.0.6
 - Measures                      0.0.2
 - NaNMath                       0.2.1
 - Optim                         0.5.0
 - PDMats                        0.4.2
 - PositiveFactorizations        0.0.1
 - Reexport                      0.0.3
 - Rmath                         0.1.2
 - SHA                           0.1.2
 - Showoff                       0.0.7
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.0
 - URIParser                     0.1.5
 - WoodburyMatrices              0.1.5

**Comment by Keno** [comment]
> Is Julia v0.4.6 not supported?

It is not
