### ISSUE TITLE
Will Gallium support IJulia in the future?

### ISSUE THREAD

**Issue by AStupidBear** [Keno/Gallium.jl#147]

**Comment by ViralBShah** [comment]
I don't think Jupyter supports debuggers - so not until then.

**Comment by tkelman** [comment]
JupyterLab might have some better debugger support coming in the future?

**Comment by ViralBShah** [comment]
Maybe - but this isn't the place to discuss it.

**Comment by tkelman** [comment]
Worth at least mentioning somewhere.

**Comment by cstjean** [comment]
Jupyter has had debugger support for as long as I've used it. After an error in a Python notebook, press `%debug`, then it goes into a "console mode" to run `pdb`. 

![screen shot 2016-09-29 at 19 26 09](https://cloud.githubusercontent.com/assets/8622776/18975789/a72dd1a2-867a-11e6-8ce5-eabcd7876f77.png)

It'd be awesome to have it work for Julia.

**Comment by AStupidBear** [comment]
Debug.jl  can do this before, but now it's deprecated
