### ISSUE TITLE
Julia Install Fail - Help Please

### ISSUE THREAD

**Issue by boogerjackson** [Keno/Gallium.jl#158]
Here is what Juno is telling me on the first run:

> PowerShell version < 3 encountered. Running without wrapper (interrupts won't work).
> INFO: Precompiling module Atom.
> ERROR: LoadError: error compiling init: could not load library "C:\Users\tmidkiff.julia\v0.5\Gallium\src\Hooking\hooking"
> %1 is not a valid Win32 application.
> 
> in include_from_node1 at .\loading.jl:488
>  in eval at .\boot.jl:234
>  in process_options at .\client.jl:239
>  in _start at .\client.jl:318
> while loading C:\Users\tmidkiff.julia\v0.5\Gallium\src\Gallium.jl, in expression starting on line 975
> ERROR: LoadError: LoadError: LoadError: Failed to precompile Gallium to C:\Users\tmidkiff.julia\lib\v0.5\Gallium.ji.
>  in compilecache at .\loading.jl:593
>  in require at .\loading.jl:393
>  in include_from_node1 at .\loading.jl:488 (repeats 3 times)
>  in eval at .\boot.jl:234
>  in process_options at .\client.jl:239
>  in _start at .\client.jl:318
> while loading C:\Users\tmidkiff.julia\v0.5\Atom\src\debugger\stepper.jl, in expression starting on line 111
> while loading C:\Users\tmidkiff.julia\v0.5\Atom\src\debugger/debugger.jl, in expression starting on line 5
> while loading C:\Users\tmidkiff.julia\v0.5\Atom\src\Atom.jl, in expression starting on line 17
> ERROR: LoadError: Failed to precompile Atom to C:\Users\tmidkiff.julia\lib\v0.5\Atom.ji.
>  in compilecache(::String) at .\loading.jl:593
>  in require(::Symbol) at .\loading.jl:422
>  in include_from_node1(::String) at .\loading.jl:488
>  in process_options(::Base.JLOptions) at .\client.jl:262
>  in _start() at .\client.jl:318
> while loading C:\Users\tmidkiff.atom\packages\julia-client\script\boot.jl, in expression starting on line 29
> Julia has stopped: 1

I have read through the other topics and tried the suggestions I saw:

> 
> julia> Pkg.update()
> INFO: Updating METADATA...
> INFO: Computing changes...
> INFO: No packages to install, update or remove
> 
> julia> using Atom
> INFO: Precompiling module Atom.
> ERROR: LoadError: error compiling init: could not load library "C:\Users\tmi
> dkiff.julia\v0.5\Gallium\src\Hooking\hooking"
> %1 is not a valid Win32 application.
> 
> in include_from_node1 at .\loading.jl:488
>  in eval at .\boot.jl:234
>  in process_options at .\client.jl:239
>  in _start at .\client.jl:318
> while loading C:\Users\tmidkiff.julia\v0.5\Gallium\src\Gallium.jl, in expressio
> n starting on line 975
> ERROR: LoadError: LoadError: LoadError: Failed to precompile Gallium to C:\Users
> \tmidkiff.julia\lib\v0.5\Gallium.ji.
>  in compilecache at .\loading.jl:593
>  in require at .\loading.jl:393
>  in include_from_node1 at .\loading.jl:488 (repeats 3 times)
>  in eval at .\boot.jl:234
>  in process_options at .\client.jl:239
>  in _start at .\client.jl:318
> while loading C:\Users\tmidkiff.julia\v0.5\Atom\src\debugger\stepper.jl, in exp
> ression starting on line 111
> while loading C:\Users\tmidkiff.julia\v0.5\Atom\src\debugger/debugger.jl, in ex
> pression starting on line 5
> while loading C:\Users\tmidkiff.julia\v0.5\Atom\src\Atom.jl, in expression star
> ting on line 17
> ERROR: Failed to precompile Atom to C:\Users\tmidkiff.julia\lib\v0.5\Atom.ji.
>  in compilecache at .\loading.jl:593
>  in require at .\loading.jl:422
> 
> julia> using Gallium
> INFO: Precompiling module Gallium.
> ERROR: LoadError: error compiling init: could not load library "C:\Users\tmi
> dkiff.julia\v0.5\Gallium\src\Hooking\hooking"
> %1 is not a valid Win32 application.
> 
> in include_from_node1 at .\loading.jl:488
>  in eval at .\boot.jl:234
>  in process_options at .\client.jl:239
>  in _start at .\client.jl:318
> while loading C:\Users\tmidkiff.julia\v0.5\Gallium\src\Gallium.jl, in expressio
> n starting on line 975
> ERROR: Failed to precompile Gallium to C:\Users\tmidkiff.julia\lib\v0.5\Gallium
> .ji.
>  in compilecache at .\loading.jl:593
>  in require at .\loading.jl:422
> 

This is julia v 0.5 on Windows 7 and atom v 1.10.2

Thank you for your help

**Comment by boogerjackson** [comment]
FYI, I have deleted Gallium, removed the cache, added Gallium, ran Pkg.update() and am still getting the same error about Gallium.

**Comment by Keno** [comment]
Do you happen to be using 32bit windows?

**Comment by boogerjackson** [comment]
No,  I am using 64 bit windows.

**Comment by Keno** [comment]
How about the julia executable? Did you download the 32bit version? Can you post `julia> versioninfo()`?

**Comment by boogerjackson** [comment]
I just did a fresh install of everything and it is working great!  I might have have the 32 bit originally. 

Thank you for the help.
