### ISSUE TITLE
crash on breakpoint in Linux

### ISSUE THREAD

**Issue by mzaffalon** [Keno/Gallium.jl#173]
On breakpoint Gallium crashes on a simple function. This is on Linux Debian Jessie using generic Linux binaries 64 bit.

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, nehalem)

julia> breakpoint(test_func)
Locations (+: active, -: inactive, *: source):
 + test_func(a::Int64) at /home/michele/jcode.jl:2
 * Any matching method added to #test_func
 * Any matching specialization of test_func(a) at /home/michele/jcode.jl:2

julia> test_func(3)
signal (4): Illegal instruction
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f449eaf28d1)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:66
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:190
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:580
jl_toplevel_eval_in_warn at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7f46b16094df)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x7f449effd6c6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7f449eff4f2f)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 6301275 (Pool: 6300047; Big: 1228); GC: 9
Illegal instruction
```

**Comment by Keno** [comment]
Mhm, I've seen this before. Caused by the CPU being pretty old at this point. Will have to get around to replacing that code.

**Comment by mzaffalon** [comment]
Is this worth your time?

**Comment by ViralBShah** [comment]
I think core i5 is not that old. Most macbook pros are core i5, I thought.

**Comment by Keno** [comment]
Core i5 is a brand name. This particular CPU is from 2009, so older than julia itself. Still, it shouldn't be too bad to rewrite it to avoid the problematic instruction.

**Comment by mzaffalon** [comment]
```
julia> Pkg.status()
16 required packages:
 - Gallium                       0.0.4+             master

julia> using Gallium
ERROR: InitError: UndefVarError: isBSS not defined
 in (::Gallium.##21#22{ELF.Sections{ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}}},String})(::ELF.SectionRef{ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}},ELF.ELF64.SectionHeader}) at /home/michele/.julia/v0.5/Gallium/src/modules.jl:169
 in start_filter(::Gallium.##21#22{ELF.Sections{ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}}},String}, ::ELF.Sections{ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}}}) at ./iterator.jl:196
 in _collect(::UnitRange{Int64}, ::Filter{Gallium.##21#22{ELF.Sections{ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}}},String},ELF.Sections{ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}}}}, ::Base.HasEltype, ::Base.SizeUnknown) at ./array.jl:282
 in mod_for_h(::ELF.ELFHandle{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Gallium.RemotePtr{Void,UInt64}, ::String) at /home/michele/.julia/v0.5/Gallium/src/modules.jl:506
 in update_module!(::Gallium.LocalSession, ::Gallium.LazyJITModules{Dict{Gallium.RemotePtr{Void,intptrT},Any}}, ::Ptr{Void}, ::String) at /home/michele/.julia/v0.5/Gallium/src/modules.jl:288
 in update_shlibs!(::Gallium.LocalSession, ::Gallium.LazyJITModules{Dict{Gallium.RemotePtr{Void,intptrT},Any}}) at /home/michele/.julia/v0.5/Gallium/src/modules.jl:303
 in __init__() at /home/michele/.julia/v0.5/Gallium/src/Gallium.jl:923
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
 in require(::Symbol) at ./loading.jl:371
during initialization of module Gallium
```

**Comment by oskarddfa** [comment]
I still get the error. My CPU is pretty old, but I thought the commit should include also older CPUs?

`julia> function hello(x)
       a = 2x
       return x
       end
hello (generic function with 1 method)

julia> using Gallium

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Pentium(R) CPU        U5400  @ 1.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, westmere)

julia> Gallium.breakpoint(hello)
Locations (+: active, -: inactive, *: source):
 * Any matching method added to #hello
 * Any matching specialization of hello(x) at REPL[1]:2


julia> hello(2)

signal (4): Illegal instruction
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f05ba5728d1)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:66
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:190
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:580
jl_toplevel_eval_in_warn at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:590
eval at ./boot.jl:234
unknown function (ip: 0x7f07c7f0b4df)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x7f05baa77d96)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x7f05baa74f2f)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 8178238 (Pool: 8176872; Big: 1366); GC: 12
Illegal instruction (core dumped)
`
