### ISSUE TITLE
enter-ing array getindex fails

### ISSUE THREAD

**Issue by shashi** [Keno/Gallium.jl#185]
```julia
julia> using Gallium
julia> A=rand(10);
julia> @enter A[1:4]
ERROR: BoundsError: attempt to access 0-element Array{Int64,1} at index [0]
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
```

I have seen this same error with other functions that call `@generated` functions as well.

**Comment by Keno** [comment]
This works in ASTInterpreter2, so I'll close this here. I'll pull in ASTInterpreter2 here in the near future (and remove the legacy Gallium bits).
