### ISSUE TITLE
On the kf/gallium branch I get the following lldb linker error for Cxx.jl

### ISSUE THREAD

**Issue by mdcfrancis** [Keno/Gallium.jl#25]
This is on OS X - the llvm build looked fine, any pointers ?

INFO: Building Cxx
Tuning for julia installation at: /Users/michaelfrancis/src/julia/usr/bin
    CC /Users/michaelfrancis/.julia/v0.4/Cxx/deps/build/bootstrap.o
    LINK /Users/michaelfrancis/.julia/v0.4/Cxx/deps/usr/lib/libcxxffi.dylib
ld: library not found for -llldbPluginObjCLanguage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [usr/lib/libcxxffi.dylib] Error 1

**Comment by ihnorton** [comment]
You need to comment out/remove that line and the next three (up to `ExpressionParserClang`) for now because the LLDB version in the current `kf/gallium` branch is behind the top-of-trunk used by Cxx.

**Comment by mdcfrancis** [comment]
Thanks it also needs the addition of -lcurses on line 53 for Darwin to link

**Comment by joehuchette** [comment]
I hit the same issue, and after the changes from @ihnorton and @mdcfrancis it built without error.

**Comment by iamed2** [comment]
Had this problem as well and the fix worked for me.

**Comment by Keno** [comment]
Rebased everything, so the new Cxx version should work just fine.
