### ISSUE TITLE
Terminal printing issues on OS X

### ISSUE THREAD

**Issue by AndyGreenwell** [Keno/Gallium.jl#33]
The attached screenshot shows example output printed to the screen when launching Gallium (in Terminal not iTerm) and executing a few commands at an LLDB prompt.  The active line in the window on the right hand side within that screenshot is the `julia>` prompt after the first two `LLDB>` prompts:
![screen shot 2015-09-18 at 6 06 08 pm](https://cloud.githubusercontent.com/assets/11096243/9972243/9badd48a-5e30-11e5-8566-0e6a3af62783.png)

**Comment by malmaud** [comment]
I get the same thing
