### ISSUE TITLE
Gallium is already a name for an LLVM project

### ISSUE THREAD

**Issue by SimonDanisch** [Keno/Gallium.jl#40]
Just saw this:
http://www.mesa3d.org/llvmpipe.html
https://en.wikipedia.org/wiki/Gallium3D
Will this be a problem?

**Comment by Keno** [comment]
Meh, if anybody complains I'll rename it to the `Gallium Debugger`, `GDB` for short ;).

**Comment by SimonDanisch** [comment]
haha, the perfect way out!
