### ISSUE TITLE
Breakpoints without specifying argument types

### ISSUE THREAD

**Issue by Keno** [Keno/Gallium.jl#50]
Right now breakpoints require argument types such that we can compile and hook the appropriate method. It would be good if we could just specify the method itself to hook. The problem here is that the methods we need to hook haven't necessarily all been compiled yet. Ideally we'd have some sort of callback in the base system that would allow us to listen for these events. We could also try to hook into the regular DWARF registration system, but that seems like a very roundabout way to accomplish this. cc @vtjnash @JeffBezanson for thoughts on implementation.

**Comment by StefanKarpinski** [comment]
Having a `@breakpoint foo(123, "hi")` that uses the types of the arguments might help make the interface a little friendlier too, no?

**Comment by Keno** [comment]
Yes, that's very easy to add and I will. However, I'm a little worried that people will use `@breakpoint` then when they really want `@enter`.

**Comment by JeffBezanson** [comment]
The lowest-hanging fruit is to allow `breakpoint(f)` when `f` has one method with a concrete signature. It would also be good to have a `breakpoint()` function so you have the escape hatch of triggering a breakpoint wherever you want by editing your code.

**Comment by Keno** [comment]
Fixed by a14a67b8ba2440b1d30e78fc819080c7e59f452e

**Comment by timholy** [comment]
Hooray!

I was trying to use Gallium to step through inference.jl, and it was an excellent reminder of how important a14a67b will be!
