### ISSUE TITLE
The second README example fails

### ISSUE THREAD

**Issue by ViralBShah** [Keno/Gallium.jl#53]
The first one gives me a debug prompt now. The second example still seems to not work.

````
julia> using Gallium
WARNING: module Lexer should explicitly import √ from Base

julia> @enter gcd(5, 20)
ERROR: UndefVarError: Builtin not defined
 in enter_call_expr(::Void, ::Expr) at /Users/viral/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:853
 in eval(::Module, ::Any) at ./boot.jl:243
````

**Comment by ViralBShah** [comment]
Is it possible to have CI to auto test some of these things? Cc @tkelman

**Comment by tkelman** [comment]
Probably not until it works on a non-source build of Julia. https://github.com/Keno/Cxx.jl/issues/73#issuecomment-155187314 is where we left off with building custom binaries for Cxx, it needs Keno to rebase his LLDB branch so it isn't broken with gcc 5, or we need to update the buildbot configuration.
