### ISSUE TITLE
user-friendlier printing of missing var info

### ISSUE THREAD

**Issue by JeffBezanson** [Keno/Gallium.jl#59]
Instead of referring to `DWARF` and/or DWARF.jl types, we should print things like `variable not found`, `variable present but cannot determine value` etc.

**Comment by JeffBezanson** [comment]
Much better now, but I still see e.g.

```
[4] eval_user_input(ast, backend) at REPL.jl:50
  | bt::DWARF.Expressions.MemoryLocation{UInt64} = DWARF.Expressions.MemoryLocation{UInt64}(0x00007fffc9fee928)
  | err = <optimized out>
  | ast::DWARF.Expressions.MemoryLocation{UInt64} = DWARF.Expressions.MemoryLocation{UInt64}(0x00007fffc9fee818)
```

**Comment by Keno** [comment]
That should only happen now if the DWARF is invalid and those aren't actually julia objects. If they are, there's a bug somewhere.

**Comment by Keno** [comment]
Try making sure DWARF.jl is up to date, there was a bug fix in the expression evaluator.
