### ISSUE TITLE
Document Gallium requirements

### ISSUE THREAD

**Issue by josefsachsconning** [Keno/Gallium.jl#60]
Either Gallium should work with a default 0.5 build (it does not for me), or else the requirements should be documented.  I currently use Gallium with a build that I did for Cxx, which is no longer required by Gallium.  Here is my Make.user file. Some of its contents are specific for my environment.
```
#GCC >= 5 will not work
#override USECLANG=1
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# Optional, but recommended
override LLVM_ASSERTIONS=1
# For LLDB support also
override BUILD_LLDB=1
override LLDB_DISABLE_PYTHON=1
USE_GPL_LIBS=0
OPENBLAS_DYNAMIC_ARCH=1
JULIA_CPU_TARGET=core2
```

**Comment by Keno** [comment]
Hi Josef,

now that https://github.com/Keno/Hooking.jl/issues/2 is resolved I believe that everything should work on Vanilla julia. If you do run into any trouble, please file an issue.
