### ISSUE TITLE
Breakpoint on error

### ISSUE THREAD

**Issue by timholy** [Keno/Gallium.jl#67]
Right now breaking on an error seems problematic, or at least unclear. #50 means you need to specify the exact types passed to whatever error function you plan to call.

As shown here, inlining is problematic:
```jl
julia> function foo(x, y)
           y < x && error("y is smaller than x")
           y - x
       end
foo (generic function with 1 method)

julia> using Gallium
INFO: Recompiling stale cache file /home/tim/.julia/lib/v0.5/ELF.ji for module ELF.

julia> Gallium.breakpoint(error, Tuple{ASCIIString})
Gallium.Hooking.Hook(Ptr{Void} @0x00007f0cbc68b000,UInt8[0x55,0x48,0x89,0xe5,0x41,0x57,0x41,0x56,0x41,0x55,0x41,0x54,0x53,0x48,0x83,0xec,0x48],Gallium.breakpoint_hit)

julia> foo(3, 2)
ERROR: y is smaller than x
 in foo(::Int64, ::Int64) at ./none:2
 in eval(::Module, ::Any) at ./boot.jl:237

julia> function bar(x, y)
           y < x && myerror("y is smaller than x")
           y - x
       end
bar (generic function with 1 method)

julia> @noinline myerror(str) = error(str)
myerror (generic function with 1 method)

julia> Gallium.breakpoint(myerror, Tuple{ASCIIString})
Gallium.Hooking.Hook(Ptr{Void} @0x00007f0ca9c34000,UInt8[0x55,0x48,0x89,0xe5,0x41,0x57,0x41,0x56,0x41,0x55,0x41,0x54,0x53,0x48,0x83,0xec,0x48],Gallium.breakpoint_hit)

julia> bar(3,2)
Body
├─ :($(Expr(:meta, :noinline)))
│  └─ noinline
├─ none: 1
└─ Return
   └─ Call
      ├─ Main.error
      └─ _2
```
Incidentally, notice that this backtrace is kind of confusing.

Is it possible to set a breakpoint in a generic place, e.g., `jl_error_f`? If so, this should be added to the README. At least for me personally, the number one way I'd plan to use this is the equivalent of Matlab's `dbstop if error`.

**Comment by Keno** [comment]
I'll add breakpoint-on-error very soon. Regarding inlining that's known, but not much we can do about it at the moment since we don't keep the inline map (though we will soon). For now the policy is to require `-O0` anyway, so we might as well also require `--inline=no` for correct functionality. Lastly, the tree display is only there for function for which we don't have source information (because they were defined at the REPL). That needs to be fixed as well.

**Comment by timholy** [comment]
Thanks for the explanations.

And thanks for the awesome contribution! It will cause me to change my elevator pitch on julia, in the part about "...julia isn't perfect, it has a few missing pieces...".

**Comment by Keno** [comment]
This has been implemented, but the paint's still dripping from the walls. Please file any issues.
