### ISSUE TITLE
Breakpoint management

### ISSUE THREAD

**Issue by Keno** [Keno/Gallium.jl#71]
We have a lists of low-level hooks in Hooking.hooks, but we should keep track of high-level breakpoints as well. Right now the two are one-to-one, but they will not be in the future (e.g. for line-based breakpoints). Also needs a ui for listing/removing breakpoints.

**Comment by timholy** [comment]
If you want the greedy list up front (to help with the ui design), other lovely things would include:
- conditional breakpoints
- inactivating/reactivating breakpoints without deleting/recreating them. Especially nice in conjunction with conditional breakpoints.

**Comment by josefsachsconning** [comment]
Is this a good place to request a feature that was available in the September 2015 incarnation that used LLDB?  In that, it was easy to set a breakpoint on a particular line of a Julia script without modifying the script.

**Comment by Keno** [comment]
This has all been implemented. The UI needs some polishing, but that's separate from this issue.
