### ISSUE TITLE
`using Gallium` is slow

### ISSUE THREAD

**Issue by bjarthur** [Keno/Gallium.jl#96]
```
julia> @time using Gallium
129.703856 seconds (34.41 M allocations: 3.002 GB, 0.91% gc time)
```

this is with the master version of Gallium and all it's dependencies, and after i've pre-compiled everything.  what is it doing?  can anything be done to speed it up?

**Comment by josefsachsconning** [comment]
Faster for me (also with master)
```
julia> @time using Gallium
  4.613232 seconds (6.79 M allocations: 292.084 MB, 6.73% gc time)
```

however, it seems to me that precompiling Gallium and its dependencies became much much slower a few days ago.  Sorry I can't narrow it down to a small number of commits.

**Comment by bjarthur** [comment]
my 2-minute `using` time is for OS X.  on my linux box it's just a few seconds.

i should add that this debugger is the single feature i most look forward to in 0.5.  thanks for all the hard work on it!

**Comment by Keno** [comment]
There is currently a large number of deprecations which slow things down. OS X also has to do some extra work to load the library map, but it shouldn't take 130 seconds (maybe 3 or 4). Let's wait until some of the deprecation warnings have been fixed and if it's still a problem, I'll take a look.

**Comment by bjarthur** [comment]
it's down to 11.3 sec on the latest masters.  good enough so i'll close this.  thanks!
